apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: node
  name: node
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: node
  strategy: {}
  template:
    metadata:
      name: hobbyistic-node-service
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/hobbyistic-default: "true"
        io.kompose.service: node
    spec:
      containers:
        - image: jmchughdai/node-hobby:v4
          name: node
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
